# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCarro', models.CharField(max_length=200)),
                ('corCarro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('dtNascimento', models.DateTimeField(verbose_name=b'Nascimento')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Perfil'),
        ),
    ]
